[package]
org="ballerinax"
name="azure.mysql"
version="0.1.1"
authors=["Ballerina"]
keywords=["Azure", "MySQL"]
repository="https://github.com/ballerina-platform/module-ballerinax-azure.mysql"
license=["Apache-2.0"]

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"

[build-options]
observabilityIncluded = true
